### ISSUE TITLE
Toggle service with automation

### ISSUE THREAD

**Issue by Chaosflori25** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#3]
I tried to toggle the service with an automation but it did not work. Is it possible to toggle the cards with an automation? If not, would it be possible to add this as a Feature?

**Comment by PiotrMachowski** [comment]
It is not possible to call this service from automations/scripts, as it is working only in scope of current browser. It is not possible to add this as a feature, because it would require totally different approach (similar to [browser_mod](https://github.com/thomasloven/hass-browser_mod); maybe it would be possible to add this feature to it).  Currently to do it you have to use standard [conditional card](https://www.home-assistant.io/lovelace/conditional/)
